# Test your FastAPI endpoints

GET http://127.0.0.1:8000/psychologists
Accept: application/json

###

POST http://127.0.0.1:8000/psychologists
Accept: application/json

{
    "name": "Ronis Pereira da Silva Junior",
    "crp": "12245",
    "birth_date": "1992-08-24"
}

###

PUT http://127.0.0.1:8000/psychologists/11
Accept: application/json

{
    "name": "Ranis Pereira da Silva Junior",
    "crp": "54321",
    "birth_date": "1992-08-24"
}

###


DELETE http://127.0.0.1:8000/psychologists/11
Accept: application/json

###