"""initial migration

Revision ID: 1db386758215
Revises: 
Create Date: 2025-10-11 18:58:47.203144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1db386758215'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idadi_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('psychologists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('crp', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idadi_normative_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initial_age_range', sa.Integer(), nullable=False),
    sa.Column('final_age_range', sa.Integer(), nullable=False),
    sa.Column('raw_score', sa.Integer(), nullable=False),
    sa.Column('developmental_score', sa.Float(), nullable=False),
    sa.Column('lower_confidence_interval', sa.Float(), nullable=False),
    sa.Column('upper_confidence_interval', sa.Float(), nullable=False),
    sa.Column('z', sa.Float(), nullable=False),
    sa.Column('standardized', sa.Integer(), nullable=False),
    sa.Column('see', sa.Float(), nullable=False),
    sa.Column('information', sa.Float(), nullable=False),
    sa.Column('id_domain', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_domain'], ['idadi_domains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('gender', sa.Text(), nullable=False),
    sa.Column('id_psychologist', sa.Integer(), nullable=False),
    sa.Column('father', sa.String(), nullable=False),
    sa.Column('father_profession', sa.String(), nullable=False),
    sa.Column('mother', sa.String(), nullable=False),
    sa.Column('mother_profession', sa.String(), nullable=False),
    sa.Column('photo', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_psychologist'], ['psychologists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('programs_upload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('generated', sa.Boolean(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('id_psychologist', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_psychologist'], ['psychologists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idadi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocol_age', sa.Integer(), nullable=False),
    sa.Column('application_date', sa.DateTime(), nullable=False),
    sa.Column('id_patient', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_patient'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('demand_description', sa.String(), nullable=True),
    sa.Column('instruments_used', sa.String(), nullable=True),
    sa.Column('idadi_analysis', sa.String(), nullable=True),
    sa.Column('anamnese_analysis', sa.String(), nullable=True),
    sa.Column('anamnese_result', sa.String(), nullable=True),
    sa.Column('conclusion', sa.String(), nullable=True),
    sa.Column('id_patient', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_patient'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_patient', sa.Integer(), nullable=False),
    sa.Column('evaluation_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_patient'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idadi_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_score', sa.Integer(), nullable=False),
    sa.Column('standard_score', sa.Integer(), nullable=False),
    sa.Column('id_domain', sa.Integer(), nullable=False),
    sa.Column('id_idadi', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_domain'], ['idadi_domains.id'], ),
    sa.ForeignKeyConstraint(['id_idadi'], ['idadi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pti_stimulus_areas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id_pti', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_pti'], ['pti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pti_specific_objectives_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id_pti_stimulus_area', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_pti_stimulus_area'], ['pti_stimulus_areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pti_specific_objectives_subtopics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id_pti_specific_objectives_topics', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_pti_specific_objectives_topics'], ['pti_specific_objectives_topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pti_specific_objectives_subtopics')
    op.drop_table('pti_specific_objectives_topics')
    op.drop_table('pti_stimulus_areas')
    op.drop_table('idadi_values')
    op.drop_table('pti')
    op.drop_table('patient_records')
    op.drop_table('idadi')
    op.drop_table('programs_upload')
    op.drop_table('patients')
    op.drop_table('idadi_normative_tables')
    op.drop_table('psychologists')
    op.drop_table('idadi_domains')
    # ### end Alembic commands ###
