"""changing patient nullabe fields

Revision ID: 36721c734dc6
Revises: 886c042ae0f8
Create Date: 2025-10-15 19:58:25.637120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36721c734dc6'
down_revision: Union[str, Sequence[str], None] = '886c042ae0f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'father',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('patients', 'father_profession',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('patients', 'mother',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('patients', 'mother_profession',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('patients', 'photo',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'photo',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('patients', 'mother_profession',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('patients', 'mother',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('patients', 'father_profession',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('patients', 'father',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
